# Generated by Django 3.1.3 on 2020-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(default='', max_length=240)),
                ('products', models.ManyToManyField(to='shop.Product')),
            ],
        ),
    ]
