# Generated by Django 3.1.3 on 2020-11-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reputation',
            options={'ordering': ['charisma_modifier']},
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('charisma_modifier', models.IntegerField()),
                ('reputation', models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='players.reputation')),
            ],
        ),
    ]
