# Generated by Django 3.1.3 on 2020-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20201127_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='remote_image_url',
            field=models.URLField(default='https://cdn2.iconfinder.com/data/icons/dragonball-z-glyph/48/Cartoons__Anime_Dragonball_Artboard_1-512.png', max_length=400),
        ),
    ]
